# Generated by Django - Initial migration for news app

import uuid
from django.db import migrations, models
import django.db.models.deletion
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('economy', 'Economy'), ('market', 'Market (Commodities)'), ('health', 'Health'), ('technology', 'Technology'), ('industry', 'Industry')], help_text='Category identifier', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable category name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this category covers')),
                ('keywords', models.JSONField(default=list, help_text='List of keywords used for category detection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether automatic fetching is enabled (fetch parameter)')),
                ('interval_seconds', models.IntegerField(default=300, help_text='Interval between scraping runs in seconds')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Timestamp of last scraper run', null=True)),
                ('last_article_url', models.URLField(blank=True, help_text='URL of most recently scraped article', max_length=1000)),
                ('articles_fetched_total', models.IntegerField(default=0, help_text='Total number of articles fetched')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scraper Configuration',
                'verbose_name_plural': 'Scraper Configurations',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the article', primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, help_text='Article headline', max_length=500)),
                ('content', models.TextField(help_text='Full article text content')),
                ('summary', models.TextField(blank=True, help_text='Article summary (AI-generated or extracted)')),
                ('url', models.URLField(help_text='Original Bloomberg article URL', max_length=1000, unique=True)),
                ('author', models.CharField(blank=True, help_text='Article author(s)', max_length=200)),
                ('image_url', models.URLField(blank=True, help_text='Featured image URL', max_length=1000, null=True)),
                ('category_confidence', models.FloatField(default=0.0, help_text='AI confidence score for category (0.0 to 1.0)')),
                ('keywords', models.JSONField(default=list, help_text='Extracted keywords with relevance scores')),
                ('entities', models.JSONField(default=dict, help_text='Named entities: companies, people, locations, etc.')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Original publication timestamp', null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When article was scraped')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(help_text='PostgreSQL full-text search vector', null=True)),
                ('is_indexed', models.BooleanField(default=False, help_text='Whether article is indexed in search engine')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether AI processing is complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Article category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [
                    django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='news_article_search_gin_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, help_text='User search query', max_length=500)),
                ('results_count', models.IntegerField(default=0, help_text='Number of results returned')),
                ('category_detected', models.CharField(blank=True, help_text='Auto-detected category', max_length=50, null=True)),
                ('category_confidence', models.FloatField(default=0.0, help_text='Category detection confidence')),
                ('execution_time_ms', models.IntegerField(default=0, help_text='Query execution time in milliseconds')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='User IP for analytics', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
