# Generated by Django 5.0.1 on 2025-12-03 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_enable_pg_trgm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at", "-scraped_at"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.RenameIndex(
            model_name="article",
            new_name="news_articl_search__6fe81f_gin",
            old_name="news_article_search_gin_idx",
        ),
        migrations.RemoveField(
            model_name="searchquery",
            name="category_confidence",
        ),
        migrations.RemoveField(
            model_name="searchquery",
            name="category_detected",
        ),
        migrations.RemoveField(
            model_name="searchquery",
            name="user_agent",
        ),
        migrations.RemoveField(
            model_name="searchquery",
            name="user_ip",
        ),
        migrations.AddField(
            model_name="searchquery",
            name="detected_category",
            field=models.ForeignKey(
                blank=True,
                help_text="AI-detected category from query",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_queries",
                to="news.category",
            ),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="execution_time_ms",
            field=models.IntegerField(
                default=0, help_text="Search execution time in milliseconds"
            ),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category", "published_at"],
                name="news_articl_categor_a51228_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_indexed", "is_processed"],
                name="news_articl_is_inde_e68831_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-scraped_at"], name="news_articl_scraped_a46746_idx"
            ),
        ),
    ]
